swagger: '2.0'
info:
  version: v0.0.0
  title: Boops API
  description: Swagger contract for Boops application
schemes:
  - http
  - https
paths:
  /auth/login:
    post:
      tags:
        - Authentication
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: filter
          in: body
          description: Contains the credentials
          required: false
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
      responses:
        '200':
          description: Ok. Returns the authorization tokens
          schema:
              $ref: '#/definitions/User'
        '400':
          description: Bad data
        '404':
          description: Service not found
        '422':
          description: Invalid username/password supplied
        '500':
          description: Internal Server Error.

  /api/v1/location/{location_id}:
    get:
      tags:
        - Locations
      produces:
        - application/json
      parameters:
        - name: location_id
          in: path
          description: id of the location to search for
          required: true
          type: number
          format: int
      responses:
        '200':
          description: Ok. Return information related to a location for a given location_id
          schema:
            $ref: '#/definitions/Location'
        '400':
          description: Bad data
        '401':
          description: Unauthorized
        '404':
          description: Service not found
        '500':
          description: Internal Server Error.

  /api/v1/location:
    post:
      tags:
        - Locations
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: location
          in: body
          description: location to add or update
          required: true
          schema:
            $ref: '#/definitions/Location'
      responses:
        '200':
          description: Ok. Returns the location added or updated
          schema:
              $ref: '#/definitions/Location'
        '400':
          description: Bad data
        '404':
          description: Service not found
        '422':
          description: Invalid username/password supplied
        '500':
          description: Internal Server Error.

  /api/v1/calendar:
    post:
      tags:
        - Calendar
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: calendar
          in: body
          description: calendar to add or update
          required: true
          schema:
            $ref: '#/definitions/Calendar'
      responses:
        '200':
          description: Ok. Returns the calendar added or updated
          schema:
              $ref: '#/definitions/Calendar'
        '400':
          description: Bad data
        '404':
          description: Service not found
        '422':
          description: Invalid username/password supplied
        '500':
          description: Internal Server Error.

  /api/v1/search_calendar:
    post:
      tags:
        - Calendar
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: calendar
          in: body
          description: calendar information to search for
          required: true
          schema:
            $ref: '#/definitions/Calendar'
      responses:
        '200':
          description: Ok. Returns the list of calendars for a given criteria.
          schema:
            type: array
            items:
              $ref: '#/definitions/Calendar'
        '400':
          description: Bad data
        '404':
          description: Service not found
        '422':
          description: Invalid username/password supplied
        '500':
          description: Internal Server Error.

  /api/v1/calendar_theme:
    post:
      tags:
        - Calendar
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: theme_calendar
          in: body
          description: information to create calendars following certain tags
          required: true
          schema:
            $ref: '#/definitions/ThemeCalendar'
      responses:
        '200':
          description: Ok. Returns the list of calendars for a given criteria.
          schema:
            type: array
            items:
              $ref: '#/definitions/Calendar'
        '400':
          description: Bad data
        '404':
          description: Service not found
        '422':
          description: Invalid username/password supplied
        '500':
          description: Internal Server Error.

  /api/v1/recipe:
    post:
      tags:
        - Recipes
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: recipe
          in: body
          description: recipe to add or update
          required: true
          schema:
            $ref: '#/definitions/Recipe'
      responses:
        '200':
          description: Ok. Returns the recipe added or updated
          schema:
              $ref: '#/definitions/Recipe'
        '400':
          description: Bad data
        '404':
          description: Service not found
        '422':
          description: Invalid username/password supplied
        '500':
          description: Internal Server Error.

  /api/v1/search_recipe:
    post:
      tags:
        - Recipes
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: recipe
          in: body
          description: recipe information to search for
          required: true
          schema:
            $ref: '#/definitions/Recipe'
      responses:
        '200':
          description: Ok. Returns the list of recipes for a given criteria.
          schema:
            type: array
            items:
              $ref: '#/definitions/Recipe'
        '400':
          description: Bad data
        '404':
          description: Service not found
        '422':
          description: Invalid username/password supplied
        '500':
          description: Internal Server Error.

  /api/v1/tags:
    post:
      tags:
        - Recipes
      produces:
        - application/json
      consumes:
        - application/json     
      parameters:
        - name: recipe
          in: body
          description: recipe information to search for
          required: true
          schema:
            $ref: '#/definitions/Recipe'
      responses:
        '200':
          description: Ok. Return list of all tags used in recipes in that location.
          schema:
            type: array
            items:
              type: string
        '400':
          description: Bad data
        '401':
          description: Unauthorized
        '404':
          description: Service not found
        '500':
          description: Internal Server Error.

  /api/v1/search_ingredient:
    post:
      tags:
        - Ingredients
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: ingredient
          in: body
          description: ingredient information to search for
          required: true
          schema:
            $ref: '#/definitions/Ingredient'
      responses:
        '200':
          description: Ok. Returns the list of ingredients for a given criteria.
          schema:
            type: array
            items:
              $ref: '#/definitions/Ingredient'
        '400':
          description: Bad data
        '404':
          description: Service not found
        '422':
          description: Invalid username/password supplied
        '500':
          description: Internal Server Error.

  /api/v1/ingredient:
    post:
      tags:
        - Ingredients
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: ingredient
          in: body
          description: ingredient to add or update
          required: true
          schema:
            $ref: '#/definitions/Ingredient'
      responses:
        '200':
          description: Ok. Returns the ingredient added or updated
          schema:
              $ref: '#/definitions/Ingredient'
        '400':
          description: Bad data
        '404':
          description: Service not found
        '422':
          description: Invalid username/password supplied
        '500':
          description: Internal Server Error.

definitions:
  Ingredient:
    type: object
    properties:
      name:
        type: string
      price:
        type: number
        format: float
        minimum: 0

  Recipe:
    type: object
    properties:
      recipe_id:
        type: number
        format: int
      name:
        type: string
      photo:
        type: string
      tags:
        type: array
        items:
          type: string
      description:
        type: string
      ingredients:
        type: array
        items:
          $ref: '#/definitions/Ingredient'

  Calendar:
    type: object
    properties:
      date:
        type: string
        format: date
      lunch_recipe_id:
        type: number
        format: int
      dinner_recipe_id: 
        type: number
        format: int

  Location:
    type: object
    properties:
      name:
        type: string
      calendars:
        type: array
        items:
          $ref: '#/definitions/Calendar'
      recipes:
        type: array
        items:
          $ref: '#/definitions/Recipe'
  
  User:
    type: object
    properties:
      username:
        type: string
      locations_id:
        type: array
        items:
          type: number
          format: int

  ThemeCalendar:
    type: object
    properties:
      tags:
        type: array
        items:
          type: string
      date_init:
        type: string
        format: date
      date_end:
        type: string
        format: date